### ISSUE TITLE
Doubt about installation

### ISSUE THREAD

**Issue by GabrielNexT** [sudosubin/zsh-poetry#1]
Hello Elvin, thanks for this plugin, starting the environment all the time was boring, even using shortcuts.

I tried to install your plugin but it is not starting the environment automatically.

The of thing I did was append the commands to .zshrc, do I need any additional configuration?

See the code bellow:
```
### End of Zinit's installer chunk
zinit light zdharma/fast-syntax-highlighting
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions
zinit ice pick'poetry.zsh'
zinit light sudosubin/zsh-poetry
```

**Comment by sudosubin** [comment]
Thanks for your report!

I found that I have removed activating environment feature, since I do not use the official poetry installation guide anymore. (https://github.com/sudosubin/zsh-poetry/commit/afcac3ca0e94a7baf7abc7e60b66c9ae16fb163c)

I will fix soon. Thanks!

**Comment by sudosubin** [comment]
I wish https://github.com/sudosubin/zsh-poetry/commit/8fa875d8eb89d1737caa81d8251b96101901d5cc might solve some problems.

But if you want `poetry shell` to be executed automatically inside poetry project, then you need to do it in your `.zshrc` by yourself.

`.zshrc` should have something like below:
```sh
precmd() {
  if [ -f './poetry.lock' ]; then
    poetry shell;
  fi
}
```

**Comment by GabrielNexT** [comment]
It worked! Thanks!

Just updating the plugin wasn't enough, I added a function in zshrc too.

Only it looks like it runs the poetry shell command 3 times, I don't know exactly why.

**Comment by GabrielNexT** [comment]
It's actually trying to run poetry shell after any command I type.

![image](https://user-images.githubusercontent.com/38765665/138691513-9c0a38ac-0393-40e6-88ee-6a2c0901951c.png)

**Comment by sudosubin** [comment]
Sorry, but I personally do not use automatic environment activation feature.
I prefer to activate the environment manually. (poetry, nvm, dotenv, ...) and I do not want to include this feature in this zsh plugin.

The snippet I left above is just an example script, and if there is a problem, I think you should fix and use it yourself.
